version: "3.9"

services:
  dev_server:
    build:
        context: ./docker-image/
        args:
            HUGO_VERSION: 0.81.0
    command: server
    volumes:
        - "./website:/src"
    ports:
        - "1313:1313"
