image: registry.gitlab.com/pages/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo -e gh-pages -s website
  artifacts:
    paths:
    - website/public
  only:
  - main
